<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\img\avataaars.svg" />
    <Content Remove="wwwroot\img\cabin.png" />
    <Content Remove="wwwroot\img\cake.png" />
    <Content Remove="wwwroot\img\circus.png" />
    <Content Remove="wwwroot\img\game.png" />
    <Content Remove="wwwroot\img\safe.png" />
    <Content Remove="wwwroot\img\submarine.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\img\avataaars.svg" />
    <None Include="wwwroot\img\cabin.png" />
    <None Include="wwwroot\img\cake.png" />
    <None Include="wwwroot\img\circus.png" />
    <None Include="wwwroot\img\game.png" />
    <None Include="wwwroot\img\safe.png" />
    <None Include="wwwroot\img\submarine.png" />
  </ItemGroup>

</Project>
